<?

/**
*
*  project  NCM_Ads
*  @file wp_blog.php
*  @user  pablo torrico
*  email  p_torrico@hotmail.com
*  url  www.neoconceptmedia.com
*  @brief   Blog of NCM_Ads
*
*         Blog based in Wordpress. The Blog should be installed into DB a7010140_db, an the tables should start with "ncm_blog_wp_"
*
*
*
*

*/


require_once("functions.php");
require_once ("header.php");
require('./blog/wordpress/wp-blog-header.php');

?>



<?  //CONTENT




echo '<div class="content">';
require_once ("blog_sidebar.php");
echo '<div class="content_text">';



write_log("Visit to pub_index/index.php");



// Get the last 3 posts.
global $post;
$args = array( 'posts_per_page' => 5 );
$myposts = get_posts( $args );

foreach( $myposts as $post ) :	setup_postdata($post); ?>
<!--<a href="
<?php // the_permalink() ?>
" rel="bookmark" title="Permanent Link to 
<?php  //the_title_attribute(); ?>
">
<?php // the_title(); ?>
</a><br /> --!>


<h1>  <? the_title(); ?> </h1>
<a> <?php the_content() ?> </a>

<?php endforeach; ?>

<?


echo '<div class="blog_nav_footer">';
echo "\n";
echo '<div class="nav_button_previous"> previous post ';
echo "\n";
echo '</div>';
echo '<div class="nav_button_next"> next post ';
echo "\n";
echo '</div>';
echo "\n";
echo '</div>';




/*
echo '<p>Los colores para Neo Concept Media son turquesa: #00b19b  y  magenta: #ff0067</p>';
*/


/*
echo '<h1>About to Neo Concept Media!</h1>

<p>Neo Concept Media to our Advertising Network and boost revenue from your website today. </p>


<p>The rigth way to monetize your web! </p>


<p>Do it right! Monteize your web with Neo Concept Media! </p>


<p>Start to generate a reliable income from your web. 
Pay Per Click (PPC) is a best method for monetize your website and your content.</p>


<p>In 2016 the trend. </p>


<p> A thousands of Buyers want to sell Advertising Online. 
Join to our Advertising Network and be payed for advertising products in your website. </p>

<p>The most intelligent way for get leads to your webstore! </p>

<br/>




<h1>Welcome to Neo Concept Media!</h1>
<p>Join your website to our Advertising Network and boost revenue from your website today.
The rigth way to monetize your web!
Do it rigth! Monteize your web with Neo Concept Media!
Start to generate a reliable income from your web. At the momento,  the Pay Per Click (PPC) is a best method for monetize your website and your content.   
In 2014 the trend.
 A thousands of Buyers want to sell Advertising Online. Join to our Advertising Network and be payed for advertising products in your website.

The most intelligent way for get leads to your webstore!
Create today a marketing campaign and take profit of the best </p>

How it works?

<p>
1.	Publishers create a campaign. After that they can add a advertising units. This advertising units concern about the content of the advertised products or services.
</p>

<p>
2.	Advertisers get the advertising code of the campaigns. They should introduce which kind of design and content want to their websites.
</p>
3.	Visitors goes to Advertiser’s website and recieve the advertising generated by the publishers.
<p>
4.	Advertisers get money   from the clicks of the visitors of their website. This money amount is variable of campaign, product and content affinity.
<p>
5.	The money which the Advertisers receive, is the money of the Publishers campaign. NCM get a procent of this campaign. 
</p>

<p>
6.	Publishers recieved visits of their websites potential customers of their products or services. NCM offers the channel, optimize the assignation between  content and advertised products , and protect of abuses.  
</p>

<p>
A Neo Concept Media system use a program for analyse and optimize the best advertising to every single web. Our system  select the best advertising for your site. </p>

<p>
Our Publishers create their campaigns and the NCM system assign a variable price per visit. The advertisers, users who owns a website and do advertising of our announces from Neo Concept Media Network,  shows advertising spaces from the running campaign from our publishers, which previously is introduced and payed. The advertisers becomes money from the clicks of the visitors into the announces. So much visitors clicking in the announces  more, money the advertisers become. 
</p>
<p>
For our business, the quality of the clicks the most important thing. For the health of our business, has the same importance that the publishers créate a campaigns and the advertisers  
 The publishers expect to  optimize the ROI of their campaigns and generate lead of potential customers.  Nowadays, the technology makes possible use the programs like robots, ghost visitors only for generate a false clicks for fraudulent propouses. The use of this kind of programs is not allowed in our system. NCM protect our Publishing users against this kind of practices. This kind of uses accounts, and traffic  will be blocked, and reported to the  “adequatly” authorities.
</p>


<h1> NEO Concept Media </h1> 
<p>
NEO Concept Media, is into continues development process. Our team is working hard to deliver a highly useful  and innovatie services for our customers.  To warrant the best performance wiht NCM can analyse their Advertising campaings of our customers. Thats why we optimizes our algorithm and code continuely, for deliver sonner as posible the best user expirience in our community.
</p>
<p>
Our system uses some of the best techniques intelligent algorithms for optimize the assignation of the content and advertising products. We can do that
We are open to listen your necessities. Please say us in which área you need help to our customer service. And we will work to acconplish your whises is our goal. 

</p>
<p>
NEO Concept Media Provide the channnel  and the tools, and the system  for generate a best satisfaction to our customers. NEO Concept Media wants to be your partner for your Company online marketing. NEO Concept  Media has something to offer to all budgets campaigns. Let us show you what we can do for you  
</p>
<h1>How works the Price assignation system? </h1>
<p>
The NCM system analyse several variables about the visit. A NCM system detect variables from the advertiser website as the visitor. This variables could be  content quality, country of the web, product, design, category, location, traget, minimun price per visit…  The system calculates  a Price for the  visit.
</p>
<p>

The Advertiser user will offer the best price for their clicks. The NCM system  calculates a price per visit analysing several factors as advertiser side like visitor side. A visitor with reported as banned ips, or visitors souspicious of be a bot click system fraud, it  will not be count as a valid clicks. Depends of which kind of traffic you generate, but as Advertiser, you must not be afraid about it, with a normal a users who has a normal use of your website, your revenues will growing!
</p>


<h2> I am a registered user.  Am I Publisher or advertiser? </h2>

<p>

All our users are Publishers and Advertisers, we want simplify more as possible the user system experience. You do not need any special activation for be Publisher or Advertiser.  
What is a campaign? What do must  for créate a campaign?
A advertising actions are divided into campaign, if you want to promote a product, website, blog or (almost) wathever…
</p>


<h2> What kind of products, services or content can I promote? </h2>
<p>
Almost whatever.  It is forbidden promote any kind of criminal content. 
Examples of not allowed content are:  drugs, children pornography or abuse, hate, racism or violence content, products or services.
 NCM it will banned this kind of content and practices. NCM has a validation system that avoid this content. In case of any legal consequences always the user will be the responsable of the legal actions. And the NCM it will collaborate with the authorities whoes has competence for figth with this not allowed character.
If you think you saw not allowed content you can notify this by our helpdesk.
</p>

<h2>If you promote some forbidden content, the amount of the payed campaign, it will not be refund. Plese use our system under your own reponsability. </h2>
<h2>For Publishers</h2>
<p>
Neo Concept Media Algorithm protect to the publisher to click fraud systems in real time. Some Users generate clicks just for be payed about it, our intelligent system of NCM recognize this dishonest behavior and does not count this clicks, and banned this users. As a result, our Publishers get better Return On Investment to their advertising campaigns. </p>

<p>
You can pay your campaign with Paypal. </p>

<p>
Our service help you to get best results for less money! 
</p>

<h2>For Advertisers</h2>
<p>
Better Pay Rolls as Adsense. Our system select your target group and get the best valuable campaign for your web!Or  system analyse your content and which Ad is optimal for your website. Nevertheless, you as advertiser can select whicht kind of advertising want to serve.
</p>

<p>You can select how many want to get for click. Our Publishers will see that in our system and notify you when a Publisher want to publish their Ad in your website. </p>
<p>Join us to our Advertising Network and start getting  new revenue streams!
You can be payed since 15$!</p>

<p> We are working to get the best service to our users. At the moment we are working hard to offer a best tools for do easily your life! </p>

<h2>About our system</h2>
<p>Our internal system assign automaticly which Price you get for the visitor. Depends of several factors, the system assign how many money the user get for the visit. Our system calculates a  

The process is so easy. Just register in our system and select which section want to 
Our high advanced system select the more desirable offer to you. NCM select the optimized option for the content of your website. The objective of our Publishers is sell more, and our objetive the satisfaction of our customers.
Join us, add the banner, and start to get money from your Website! </p>
<p>Easy to use! </p>
<p>
We have different programs for promote your web. 
You can use and earn money only sharing links, to your Friends and social networks.
How Works our system.
</p>

<h2>We are working hard for give you a innovative system! join </h2>
<p>
How do the payments process are do?
 Once the user has a 15.000 visits of NCM system realize thats a payment is posible. You can see in Settings.php the option of payment is disblocked.  You must to request the payment and it will be approved. By the end of the month we will transfer the money to your paypal account.

Which pay methods are supported?
We use paypal or bank transfer, because is widely extended. 
</p>
<h2>I need help, who can help me? </h2>
<p>Please contact with our helpdesk. They will help you. We are glad in be useful to our users. 
I think your system could much be better if you offer this option, have a propouse for you?
Please do not hesitate to contact with us, througt our helpdesk. We are glad in helping our users. </p> ';



echo '<div><a align="left"  href=blog.php?page=.$actual_page+1.>next</a> </div>';

echo '<div><a class=next_button href=blog.php?page=.$actual_page-1>prev</a> </div> ';

*/


if (user_logged_in() == 1){

//   echo '<div class="content_text" ><h1>  Your user is logged in and you have access to registered content </h1></div>';
  
  }
   else{}






?>

<?
require_once ("footer.php")

?>